FROM openjdk:21-jdk-slim AS builder

##FROM GIT

## Install git on ubuntu
#RUN apt-get update     
#RUN apt-get install -y git

## Install git on alpine
#RUN apk update
#RUN apk add git

## Use this path as the default location for all subsequent commands
#WORKDIR /app

## Clone source code to local image
#RUN git clone https://github.com/k2x2048/jgsu-spring-petclinic.git
#RUN git clone git@github.com:k2x2048/jgsu-spring-petclinic.git

# Use this path as the default location for all subsequent commands
#WORKDIR /app/jgsu-spring-petclinic


#FROM LOCAL

# Use this path as the default location for all subsequent commands
WORKDIR /app

#Copy Maven wrapper and pom.xml
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

#Copy Maven packages
#COPY .m2/ ~/.m2


# Download/install dependencies.
RUN ./mvnw dependency:resolve

#Copy source code
COPY src ./src

# Build app
RUN ./mvnw package


#FROM openjdk:21-jre-slim
#FROM tomcat:9.0.71-jre8-temurin-focal
FROM tomcat:jre8-alpine
#FROM node:lts-alpine3.17

# Use this path as the default location for all subsequent commands
WORKDIR /app

# Copy builed website
COPY --from=builder /app/target/spring-petclinic-*.jar ./spring-petclinic.jar

# Define webserver port
EXPOSE 8080 8000

# Start webserver
CMD ["java", "-jar", "spring-petclinic.jar"]
