version: '3.8'

services:

  gitlab: #GitLab server
    container_name: gitlab
    image: gitlab/gitlab-ce:13.8.8-ce.0
    ports:
      - "22:22"
      - "443:443"
      - "8081:80"
    volumes:
      - /etc/gitlab
      - /var/log/gitlab
      - /var/opt/gitlab
    networks:
      - jenkins_net
    restart: unless-stopped


  jenkins:
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    depends_on:
      - dind
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-docker-certs:/certs/client:ro
    environment:
      DOCKER_HOST: "tcp://dind:2375"
      DOCKER_TLS_CERTDIR: "/certs"
    networks:
      - jenkins_net
    restart: unless-stopped


  dind:
    image: docker:dind
    user: root
    privileged: true
    container_name: dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    expose:
      - 2375
    networks:
      - jenkins_net
    restart: unless-stopped
  
  ssh-agent:
    image: jenkins/ssh-agent


  sonar:
    container_name: sonarqube
    image: sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - /etc/gitlab
      - /var/log/gitlab
      - /var/opt/gitlab

networks:
  jenkins_net:
    driver: bridge