FROM jenkins/jenkins:lts-jdk11
# FROM jenkins/jenkins:2.393
# FROM jenkins/jenkins:2.393-jdk11
# FROM jenkins/jenkins:2.393-jdk17
# FROM jenkins/jenkins:2.393-alpine
# FROM jenkins/jenkins:2.393-alpine-jdk17
# FROM jenkins/blueocean:

USER root
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
# RUN apt-get update && apt-get install -y docker-ce-cli
RUN usermod -aG docker jenkins
USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"