---
- name: Install, configure, and start an Nginx web server

  block:
    - name: Update and upgrade apt
      become: true
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: yes
 

    - name: "Install Nginx"
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present


    - name: Copy the Nginx configuration file to the host
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        

    - name: Create link to the new config to enable it
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link


    - name: Create Nginx directory
      ansible.builtin.file:
        path: /home/ubuntu/nginx
        state: directory
 
    - name: Copy index.html to the Nginx directory
      copy:
        src: files/index.html
        dest: /home/ubuntu/nginx/index.html
        mode: 0644
      notify: Restart the Nginx service
      when: ansible_facts['distribution'] == 'Ubuntu'
      tags: nginx
      become: true
      become_user: root

    - name: restart nginx
      service:
        name: nginx
        state: restarted
