{
 "title": "spider-crawler-task-monitor",
 "description": "spider-crawler-task-monitor with docker\r\ncontract me:https://github.com/zengfr",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "dup",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(my_scheduler_task_duplicate_total{}[1m])",
     "legendFormat": "dup-{{instance}}"
    }
   ]
  },
  {
   "title": "del",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(my_scheduler_task_queue_host_del_total{}[1m])",
     "legendFormat": "host-{{instance}}"
    },
    {
     "expr": "increase(my_scheduler_task_queue_url_del_total{}[1m])",
     "legendFormat": "url-{{instance}}"
    }
   ]
  },
  {
   "title": "push",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(my_scheduler_task_push_total{}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pull",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(my_scheduler_task_pull_total{}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dld",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(my_scheduler_task_download_total{}[1m])",
     "legendFormat": "dld_{{instance}}_{{code}}"
    }
   ]
  },
  {
   "title": "dld sum",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(my_scheduler_task_download_total{}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "dld sum 2",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(my_scheduler_task_download_total{}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}