version: "3"
services:
    sonarqube:
        depends_on:
            - db
        image: sonarqube:9.9.0-community
        # image: sonarqube:latest
        # image: sonarqube:lts-community
        # image: sonarqube:9.9.0-enterprise
        # image: sonarqube:9.9.0-developer
        # image: sonarqube:9.9.0-community
        # container_name: sonarqube
        # hostname: sonarqube
        restart: unless-stopped
        environment:
            # - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube # depreciated
            # - SONARQUBE_JDBC_USERNAME=sonarqube # depreciated
            # - SONARQUBE_JDBC_PASSWORD=sonarpass # depreciated
            - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
            # - sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube
            - sonar.jdbc.username=admin
            - sonar.jdbc.password=sonar
        expose:
            - "9000"
        ports:
            - "9000:9000"
            # - "127.0.0.1:9000:9000"
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            # - sonarqube_logs:/opt/sonarqube/logs
            # - sonarqube_temp:/opt/sonarqube/temp
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
        networks:
            - sonarqube

    db:
        image: postgres:15.2
        # image: postgres:latest
        restart: unless-stopped
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=sonar
            - POSTGRES_DB=sonar
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
        networks:
            - sonarqube

volumes:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_logs:
    sonarqube_temp:
    sonarqube_extensions:
    sonarqube_bundled-plugins:

    postgresql:
    postgresql_data:

networks:
    sonarqube: