global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "prometheus_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
      labels:
        group: 'MyAlertmanager'

scrape_configs:

  - job_name: 'cadvisor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        group: 'Mycadvisor'

  - job_name: 'node-exporter-tls'
    scheme: https
    basic_auth:
      username: prometheus
      password: prometheus
      # password_file: '/etc/node-exporter/passwordfile.txt' # error
    tls_config:
      ca_file: node_exporter.crt
      insecure_skip_verify: true
    static_configs:
    - targets: ['node_exporter:9100']
      labels:
        instance: 'MyNodeExporter'

  - job_name: 'prometheus'
    # metrics_path: /prometheus
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:9090']
      labels:
        group: 'MyPrometheus'

  - job_name: 'Test'
    static_configs:
    - targets: 
      - grafana:3000
      - alertmanager:9093
      - node-test1:9100
      - error455:4000
      labels:
        group: 'MyContainers'
