groups:
  - name: AllInstances
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        title: 'test title'
        summary: "Instance [{{ $labels.instance }}] down"
        description: "[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 1 minute."
  
  - name: MyContainers
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        title: 'test title 2'
        summary: "Instance [{{ $labels.instance }}] down"
        description: "[{{ $labels.instance }}] of job [{{ $labels.job }}] has been down for more than 0 minute."