FROM gradle:jdk8 AS builder0

# Use this path as the default location for all subsequent commands
WORKDIR /app

#Copy source code
COPY *.gradle .
COPY src ./src

# Test app
RUN gradle test

# Build app
RUN gradle build --no-daemon


#OPTIMIZE SIZE
FROM openjdk:17-alpine AS builder

# Use this path as the default location for all subsequent commands
WORKDIR /app

# copy the executable jar into the docker image
COPY --from=builder0 app/build/libs/*.jar build/app.jar

# Create a custom JRE 
RUN jlink --verbose \
--compress 2 \
--strip-java-debug-attributes \
--no-header-files \
--no-man-pages \
--output jre \
--add-modules java.base

#**********************************************************

FROM alpine:3.16.1

# Use this path as the default location for all subsequent commands
WORKDIR /app

COPY --from=builder /app/jre jre

# copy the app
COPY --from=builder /app/build/app.jar .

# run the app on startup
ENTRYPOINT /app/jre/bin/java -jar app.jar