version: '3.8'

services:

  petclinic_webserver: # PetClinic Webserver
    #container_name: mycontainername
    build: # Build an image with all needed dependencies
      context: ./ # Use this base path for all commands in dockerfile
      dockerfile: ./docker/dockerfile # Specify dockerfile path
    #hostname: myhostname
    image: tomcatpetvlinicsql:1.0
    ports:
      - "8000:8000"
      - "80:8080"
    depends_on:
      - mysqlserver
    restart: unless-stopped
    #stdin_open: true # keep open the terminal after building container
    #tty: true # keep open the terminal after building container

  mysqlserver:
    #container_name: mycontainername
    #image: mysql:5.7
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    #hostname: myhostname
    ports:
      - "3306:3306"
    volumes:
      #- "./docker/sqlinit/:/docker-entrypoint-initdb.d/:ro"
      #- "./sqlconfig/conf.d:/etc/mysql/conf.d"
      - "mysql_data:/var/lib/mysql"
    restart: unless-stopped

volumes:
  mysql_data:
  maven_repo:
